# -*- coding: utf-8 -*-
"""MovieAnalysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dYRmFtlPdcohBB9AhHFWFWZdmJgXwuXk
"""

import pandas as pd
url="/content/IMDb_All_Genres_etf_clean1.csv"
data=pd.read_csv(url)
data

data.head()

data.tail()

data.groupby('Year').size()

data.shape

data.ndim

data.dtypes

data['Year'].describe()

data['Year']==2022

data.Year.unique()

pd.Categorical(data)

data.isnull()

data.notnull()

data.isnull().sum()

data.dropna()

rat = data['Rating']
mean_m = rat.mean()
mean_m

median_m = rat.median()
median_m

mode_m=rat.mode()
mode_m

from matplotlib import pyplot as plt
fig = plt.figure(figsize=(10,5))
ax = fig.add_axes([0,0,1,1])
plt.hist(rat,bins=100,color='grey')
plt.axvline(mode_m[0],color='pink',label='mode')
plt.axvline(mean_m,color='green',label='mean')
plt.axvline(median_m,color='yellow',label='median')
plt.legend()
plt.show()

rat.min()

rat.max()

rat.max()-rat.min()

rat.var()

from math import sqrt
std=sqrt(rat.var())
std

import numpy as np
np.percentile(data['Rating'],50)

rat.quantile(0.5)

q75=np.percentile(data['Rating'],75)
q75

q3=rat.quantile(0.75)
q3

q25=np.percentile(data['Rating'],25)
q25

q1=rat.quantile(0.25)
q1

IRQ=q3-q1
IRQ

plt.boxplot(rat)
plt.show()

rat.skew()

rat.kurt()

data.groupby('Year').count()

data.groupby('Director').size()

data.groupby('main_genre').size()

data1 = pd.DataFrame(data)
data1

x=data1.Rating
x

y=data1.Year
y

x.corr(y)

xy = pd.DataFrame({'Year':x,'Rating':y})
matrix = xy.corr()
matrix

x.corr(y, method = 'kendall')

matrix = xy.corr(method='kendall')
matrix

x.corr(y, method='spearman')

matrix = xy.corr(method='spearman')
matrix

sort = data.sort_values(by='Rating', ascending = False)
sort

sort.head(10)

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/IMDb_All_Genres_etf_clean1.csv")

df['Year'] = pd.to_datetime(df['Year'], format='%Y')
df['Year'] = df['Year'].dt.year

movie = df.groupby('Year')['Movie_Title'].count()
rating = df.groupby('Year')['Rating'].sum()

fig, ax1 = plt.subplots()
ax1.set_xlabel('Year')
ax1.set_ylabel('Number of Moviee', color='grey')
ax1.plot(movie.index, movie.values, color='green')
plt.show()

director_rat = data.groupby('Director')['Rating'].mean().reset_index()
top_director = director_rat.sort_values(by='Rating', ascending =False)
top_director

import numpy as np
from sklearn import preprocessing
rat= np.array(data['Rating'])
normal = preprocessing.normalize([rat])
normal

year=np.array(data['Year'])
normal = preprocessing.normalize([year])
normal

runtime = np.array(data['Runtime(Mins)'])
normal = preprocessing.normalize([runtime])
normal

